version: '3.4'

services:
  efcoreissuetest:
    image: ${DOCKER_REGISTRY-}efcoreissuetest
    build:
      context: .
      dockerfile: EFCoreIssueTest/Dockerfile
  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: ${DOCKER_REGISTRY-}sql-dev 
    ports: 
     - 2433:1433 
    environment: 
     - 'SA_PASSWORD=yourStrong(!)Password' 
     - 'ACCEPT_EULA=Y' 
     - 'MSSQL_PID=Express'