version: '3.4'

services:
  dockerenvtest2:
    image: ${DOCKER_REGISTRY-}dockerenvtest2
    build:
      context: .
      dockerfile: DockerEnvTest2/Dockerfile
  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-dev
    ports: 
    - 2433:1433
    environment:
    - 'SA_PASSWORD=yourStrong(!)Password'
    - 'ACCEPT_EULA=Y'
    - 'MSSQL_PID=Express'